version: '3.8'
services:
  api:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gogin-api-cuentas-claras
    ports:
      - "5432:5432"
