// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"GoGin-API-CuentasClaras/api/auth"
	"GoGin-API-CuentasClaras/api/handlers"
	"GoGin-API-CuentasClaras/repository"
	"GoGin-API-CuentasClaras/services"
	"github.com/google/wire"
)

// Injectors from injector.go:

func Init() *Initialization {
	gormDB := ConnectToDB()
	userRepositoryImpl := repository.UserRepositoryInit(gormDB)
	operationRepositoryImpl := repository.OperationRepositoryInit(gormDB)
	categoryRepositoryImpl := repository.CategoryRepositoryInit(gormDB)
	authImpl := auth.AuthInit()
	userServiceImpl := services.UserServiceInit(userRepositoryImpl, authImpl)
	operationServiceImpl := services.OperationServiceInit(operationRepositoryImpl, categoryRepositoryImpl)
	userHandlerImpl := handlers.UserHandlerInit(userServiceImpl)
	operationHandlerImpl := handlers.OperationHandlerInit(operationServiceImpl)
	categoryServiceImpl := services.CategoryServiceInit(categoryRepositoryImpl)
	categoryHandlerImpl := handlers.CategoryHandlerInit(categoryServiceImpl)
	initialization := NewInitialization(userRepositoryImpl, operationRepositoryImpl, categoryRepositoryImpl, userServiceImpl, operationServiceImpl, userHandlerImpl, operationHandlerImpl, authImpl, categoryHandlerImpl)
	return initialization
}

// injector.go:

var db = wire.NewSet(ConnectToDB)

var userServiceSet = wire.NewSet(services.UserServiceInit, wire.Bind(new(services.UserService), new(*services.UserServiceImpl)), auth.AuthInit, wire.Bind(new(auth.Auth), new(*auth.AuthImpl)))

var operationServiceSet = wire.NewSet(services.OperationServiceInit, wire.Bind(new(services.OperationService), new(*services.OperationServiceImpl)))

var categoryServiceSet = wire.NewSet(services.CategoryServiceInit, wire.Bind(new(services.CategoryService), new(*services.CategoryServiceImpl)))

var userRepoSet = wire.NewSet(repository.UserRepositoryInit, wire.Bind(new(repository.UserRepository), new(*repository.UserRepositoryImpl)))

var operationRepoSet = wire.NewSet(repository.OperationRepositoryInit, wire.Bind(new(repository.OperationRepository), new(*repository.OperationRepositoryImpl)))

var categoryRepoSet = wire.NewSet(repository.CategoryRepositoryInit, wire.Bind(new(repository.CategoryRepository), new(*repository.CategoryRepositoryImpl)))

var userHdlerSet = wire.NewSet(handlers.UserHandlerInit, wire.Bind(new(handlers.UserHandler), new(*handlers.UserHandlerImpl)))

var operationHdlerSet = wire.NewSet(handlers.OperationHandlerInit, wire.Bind(new(handlers.OperationHandler), new(*handlers.OperationHandlerImpl)))

var categoryHdlerSet = wire.NewSet(handlers.CategoryHandlerInit, wire.Bind(new(handlers.CategoryHandler), new(*handlers.CategoryHandlerImpl)))
